all: 
	gcc cola.c -Wall -pedantic -std=c99 -g -c
	gcc pila.c -Wall -pedantic -std=c99 -g -c
	gcc lista.c -Wall -pedantic -std=c99 -g -c
	gcc lectura.c -Wall -pedantic -std=c99 -g -c
	gcc participante.c -Wall -pedantic -std=c99 -g -c
	gcc tp1.c cola.o pila.o lista.o lectura.o participante.o -Wall -pedantic -std=c99 -g -o tp1
